import '@/ui/styles/global.css';
import { inter, Footer } from '@/ui';
import ClientHeader from './client-header';

export const metadata = {
  title: 'Welcome to sharebrary',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <div className="min-h-screen bg-background text-foreground flex flex-col">
          <ClientHeader />
          <main className="flex-1 container mx-auto px-4 pt-20 pb-4">
            {children}
          </main>
          <Footer
            content={
              <>
                made with <span className="text-primary">♥</span> by przemo
              </>
            }
          />
        </div>
      </body>
    </html>
  );
}
