import './global.css';
import { Header } from '@/ui';

export const metadata = {
  title: 'Welcome to sharebrary',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen bg-background text-foreground flex flex-col">
          <Header />
          {children}
          <footer className="border-t py-4 text-center text-sm text-muted-foreground">
            made with <span className="text-primary">♥</span> by przemo
          </footer>
        </div>
      </body>
    </html>
  );
}
