name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--experimental-vm-modules --no-warnings'
      VITE_CJS_IGNORE_WARNING: 'true'
      VITE_CJS_TRACE_WARNING: 'false'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set SHAs for base and head for affected commands
        id: setSHAs
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "Setting SHAs for PR"
            echo "NX_BASE=origin/${{ github.base_ref }}" >> $GITHUB_ENV
            echo "NX_HEAD=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          else
            echo "Setting SHAs for push"
            echo "NX_BASE=origin/main~1" >> $GITHUB_ENV
            echo "NX_HEAD=${{ github.sha }}" >> $GITHUB_ENV
          fi

      # Run each command separately to isolate failures
      - name: Lint affected projects
        run: pnpm run ci:lint

      - name: Test affected projects
        run: pnpm run ci:test

      - name: Build affected projects
        run: pnpm run ci:build
